name: Deno

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v2.4.0
    - run: deno cache --lock=deno.lock src/deps.ts
    - run: deno run --allow-net --allow-read --allow-write=/home/runner/.cache/deno https://jsr.io/@db/sqlite/0.12.0/mod.ts
    - run: deno test --allow-read=.,/home/runner/.cache/deno --allow-write=test,/home/runner/.cache/deno --allow-env --allow-ffi --no-chec