name: Deno

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    # denoland/setup-deno v2.3.0
    - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb
      with:
        deno-version: v2.4.0
    - run: deno cache --lock=deno.lock src/deps.ts
    
    - name: Run tests
      run: deno test --allow-read --allow-write --allow-env --allow-ffi --allow-net
